"""
LLM 기반 Hook 분류 캐시 생성기
- 미분류 Hook 137건을 신규 유형으로 분류
- 결과를 llm_hook_cache.json에 저장
"""
import json
from pathlib import Path

BASE_DIR = Path(__file__).parent

# ─────────────────────────────────────────────
# 미분류 Hook 137건 → 신규 유형 분류 (조회수 내림차순)
# ─────────────────────────────────────────────
# 유형:
#   narrative_situation = 서사/상황형 (구체적 사건·인물의 상황 묘사)
#   info_fact           = 정보전달형 (팩트, 데이터, 지식 전달)
#   opinion_reaction    = 의견/반응형 (개인 의견, 평가, 감상)
#   celeb_mention       = 셀럽/유명인형 (특정 유명인 언급)
#   promotion           = 홍보/추천형 (제품·서비스·이벤트 홍보)
#   emotion_empathy     = 감정/공감형 (감정 호소, 공감 유도)
#   comparison_choice   = 비교/선택형 (선택지 제시, 가정 상황)

UNCLASSIFIED_LABELS = [
    "opinion_reaction",     # 1: 요새 핫한 성수동 카페라는데...
    "celeb_mention",        # 2: 유해진 172cm 박지훈 173cm...
    "narrative_situation",  # 3: 성형 NO, 외모로 놀림 받다가...
    "celeb_mention",        # 4: * AOA출신 권민아...
    "info_fact",            # 5: 낭만 다 사라진 최근 '스피노사우루스'...
    "narrative_situation",  # 6: 혼밥하면 귀여운 댕댕이가...
    "promotion",            # 7: ‼️ Team 휴학생 대학생 대학원생 주목 ‼️
    "narrative_situation",  # 8: 25살 연하 아내의 마음을 훔친...
    "info_fact",            # 9: < 구정 이후 금전 흐름 크게 트이는 띠 >
    "narrative_situation",  # 10: 임산부라 무알콜 하이볼 주문했는데...
    "opinion_reaction",     # 11: 인스타 구경하다가 18살차이 커플...
    "narrative_situation",  # 12: 50년 전 죽은 태아가 뱃속에서...
    "info_fact",            # 13: 자신의 추구하는 신념에 따라...
    "narrative_situation",  # 14: 나고야에서도 찍힌 한국인 모녀한테...
    "opinion_reaction",     # 15: 감사하다는 말 너무 난발하는 친구가...
    "narrative_situation",  # 16: 어머니가 응급실로 실려 가자...
    "narrative_situation",  # 17: 번역기 돌려보니 진짜 개웃기네...
    "celeb_mention",        # 18: 유재석과 촬영했는데 초면이라는 배우...
    "narrative_situation",  # 19: 금메달 땄는데 아무도 축하안해준...
    "narrative_situation",  # 20: 롯데 신동빈회장에게 덤빈 신입사원의 최후
    "narrative_situation",  # 21: 본인 빌딩 매입 기사에 댓글을 단...
    "comparison_choice",    # 22: 5억 준다면 서울-부산 걸어서...
    "narrative_situation",  # 23: 후원 대가로 일주일에 1~2번씩...
    "info_fact",            # 24: 오전 10시 전 출근이랑 등교가 신체에는...
    "emotion_empathy",      # 25: 어느 가을날 택시를 탔더니...
    "opinion_reaction",     # 26: 내 직업 특성상 인플루언서들 진짜 많이...
    "opinion_reaction",     # 27: 유치원 교사 투명 손톱강화제...
    "opinion_reaction",     # 28: 주변에서 삼성전자, 하이닉스로 돈 벌었다고...
    "narrative_situation",  # 29: 매장 앞에서 일하시는 분들이 작업하다가...
    "info_fact",            # 30: 연예인으로 각 쌍꺼풀 별 라인 알아보기...
    "narrative_situation",  # 31: 지나가던 남성 어깨빵에 버튼 눌러...
    "info_fact",            # 32: 추적 60 분에서 강의팔이 책팔이들을...
    "celeb_mention",        # 33: (구)충주맨 김선태 신규 유튜브 채널...
    "opinion_reaction",     # 34: 가끔 작가라 그러면 밥 벌어 먹고...
    "narrative_situation",  # 35: 1981년, 독일 여성 마리안 바흐마이어...
    "info_fact",            # 36: 홋카이도에서 매물로 나온 9500만원짜리 성
    "info_fact",            # 37: 거꾸로 박힌 이쑤시개를 찾았다면...
    "promotion",            # 38: 우왕 다이소에서 상품 택배 받고...
    "emotion_empathy",      # 39: (번역) 어딘가에서 읽은 글인데...
    "info_fact",            # 40: 조주빈 교도소에서 상받았다고...
    "celeb_mention",        # 41: 우즈가 데뷔 후 연속으로 악재가...
    "narrative_situation",  # 42: 21살 연하 여자 공무원이 날 좋아하는거...
    "narrative_situation",  # 43: 페루가 버리던 오징어 싹쓸이해서...
    "celeb_mention",        # 44: 모든 기업과 유튜버들의 러브콜을 제치고...
    "narrative_situation",  # 45: 일본의 한 라멘 가게에서 라멘을 먹은...
    "celeb_mention",        # 46: 김선태가 그냥 딸깍 생긴 유튜버라...
    "info_fact",            # 47: 60살 전에 신청 안하면 못 받는...
    "info_fact",            # 48: < 사람들이 잘 모르는 번아웃 증상 >
    "opinion_reaction",     # 49: 발렌타인데이 늘 그랬듯이 못 받는...
    "info_fact",            # 50: 경기 안산, 테이저건 맞고도 멀쩡한...
    "info_fact",            # 51: 아이폰 15 Pro 쓰고 있는데 보상판매하면...
    "opinion_reaction",     # 52: 인스타에서 인플루언서들 효소 공구...
    "narrative_situation",  # 53: 이거 한참 옛날 얘긴데, 우리회사 경우도...
    "opinion_reaction",     # 54: 이건 정말 당해보지 않고서는 이 느낌...
    "narrative_situation",  # 55: 마지막까지 펭귄들이 입을 스웨터 짜준...
    "promotion",            # 56: 기숙사생 • 자취생 • ‼️ 첫 신청자 ‼️...
    "opinion_reaction",     # 57: 세계 평화를 위해 트럼프 아들...
    "promotion",            # 58: 오픽 할인 받을 수 있는 🩵 대학연합...
    "narrative_situation",  # 59: 나 엄마한테 설 선물로 5000만원 코트...
    "opinion_reaction",     # 60: 남자고 여자고 무슨 일 하냐고 물어보면...
    "info_fact",            # 61: 우리 회사 5년 근속할 때마다 금 5돈...
    "narrative_situation",  # 62: $2.99짜리 맥주 마시는 앱으로 경제적 자유를...
    "narrative_situation",  # 63: '일부다처', 일본인 '186억 트레이더'의 삶
    "opinion_reaction",     # 64: 한국으로 이송 수감시 심장마비로 자연사 할...
    "promotion",            # 65: 오쏘뮬 이뮨 <<<< 감기에 얘 진짜 직빵이에요
    "info_fact",            # 66: 월 400만원 따박따박. 현대차 우선주...
    "celeb_mention",        # 67: 목디스크 치료 과정에서... 트와이스 정연...
    "celeb_mention",        # 68: '새벽쿠팡 직접 체험해 본다고 한 로저스 대표
    "info_fact",            # 69: <이란, 스물다섯의 얼굴에 남은 시대의 상처>
    "narrative_situation",  # 70: 탈옥을 위해 5년 간 터널 팠는데...
    "promotion",            # 71: Team 폐급(당사자성 발언) 에게 ㅊㅊ하는 사이트
    "narrative_situation",  # 72: 연락 안하고 지낸지 10년 정도된 후배가...
    "narrative_situation",  # 73: 3초안에 저격수를 못찾았다면...
    "opinion_reaction",     # 74: 오랜만에 회사 사람들이 주식 얘기를...
    "narrative_situation",  # 75: 특허를 개발하고 '가치를 매길 수 없다'...
    "promotion",            # 76: 초코라떼 먹고싶으면 디저트39 저당리얼...
    "comparison_choice",    # 77: 우리 각자 가장 좋아하는 두 글자 단어...
    "info_fact",            # 78: 한국인만 채용한다는 삼성전자 평택 건설현장 근황
    "info_fact",            # 79: 중국도 절대 못 따라오는 한국의 미친 기술력...
    "narrative_situation",  # 80: 광진구의 아파트를 12억 대출받아 영끌한...
    "opinion_reaction",     # 81: 다림질하다가 태워놓고는 디자인인 것처럼...
    "info_fact",            # 82: 나라별 손가락 욕이라는데...
    "promotion",            # 83: 이 글 3초 안에 좋아요, 알티시 로또 당첨 됨
    "narrative_situation",  # 84: 코인으로 1억 날렸습니다. 아내에게 2억...
    "opinion_reaction",     # 85: 성형관련 마케팅 분야에 종사하면서 느낀점...
    "celeb_mention",        # 86: 전 구글 디렉터 미키 킴. 장기 보유자란...
    "emotion_empathy",      # 87: 고3때 저희 어머니는 울면서 저에게...
    "narrative_situation",  # 88: 애기랑 같이 입원하면서 폐렴 바이러스가...
    "info_fact",            # 89: < 남의 시선이 신경쓰일 때 기억해야할 것 >
    "info_fact",            # 90: 요즘 국수영탐 21311이면 정시로 서성한...
    "opinion_reaction",     # 91: 일본 빼달라 -> 미국이 한국 빼버림 ㅅㅂ
    "info_fact",            # 92: 미국에서 지금 트럼프 아들 군대 보내라는...
    "info_fact",            # 93: 러닝으로 체력을 만들고, 턱걸이로 몸을...
    "celeb_mention",        # 94: 최근 '메달 오브 아너' 받아 화제인 미국 파일럿
    "opinion_reaction",     # 95: 한국만 완성되어있는게 진짜 웃기네용ㅋㅋ
    "info_fact",            # 96: 1906년에 찍힌 바르셀로나 '사그라다 파밀리아 성당'
    "info_fact",            # 97: 10. 볼보의 'XC90' 모델은 2002년 출시 이후...
    "info_fact",            # 98: 찬 밥 데워 먹으면 칼로리 반으로 줄어드는거...
    "opinion_reaction",     # 99: 오리발골이 쉬운일이 절대 아님을 알게 되었다
    "narrative_situation",  # 100: 남자 꼬시러 가는 여자 공무원 옷좀 골라줘요
    "narrative_situation",  # 101: 자취생 시절 돈 아낄때 알리오올리오를...
    "comparison_choice",    # 102: 30대 초반 남자라고 가정하고 결혼상대로 누구
    "comparison_choice",    # 103: 카페에서 음료수 안시키는 친구 얄밉다vs그럴 수...
    "narrative_situation",  # 104: 루이비통과 4 년동안 독고다이로 싸워서 이긴...
    "info_fact",            # 105: 착공 144년 만에 완공된 바르셀로나...
    "comparison_choice",    # 106: 초등학생이 길을 물어보면 반말 한다vs존댓말...
    "narrative_situation",  # 107: 4년전에 결혼해서 행복하다고 글을 썼었는데...
    "info_fact",            # 108: 항공사 바이 항공사 같아요 대한항공...
    "info_fact",            # 109: 지금 난리난 2년 전 지금 상황을 가장 정확히...
    "info_fact",            # 110: 대체에너지, 에너지자립, 재생에너지 관련주 정리
    "info_fact",            # 111: 중국, 유사시 한국 공격할 수 있다. <홍콩SCMP>
    "promotion",            # 112: 탈모, 지성 두피가 막 발라도 되는 트리트먼트...
    "narrative_situation",  # 113: 와… 어떤 사람이 스타벅스 종이에 그림 그렸는데
    "narrative_situation",  # 114: 그록에게 연쇄살인범 김소영의 머그샷과...
    "opinion_reaction",     # 115: 와 이런거 보면 X 노출 요령만 잘 알면...
    "opinion_reaction",     # 116: 개인적으로 우리나라는 사교육비 못잡으면...
    "info_fact",            # 117: 네덜란드에 망명 중인 이란 여성들이...
    "emotion_empathy",      # 118: 동생 사망 전 의식이 잠깐 돌아와 남긴말이...
    "promotion",            # 119: <정샘물 에센셜 물 마이크로 피팅 미스트>
    "narrative_situation",  # 120: 자린고비도 울고 가것네 1,000원짜릴 7년이나
    "narrative_situation",  # 121: 9살에 '세계에서 가장 아름다운 소녀'로 뽑혔던...
    "info_fact",            # 122: 이마빌딩은 풍수지리상 쇳복(즉 돈)으로...
    "celeb_mention",        # 123: * 카메라 앞 프로 의식 차이...제니 vs 고윤정
    "promotion",            # 124: 이 하트돌을 보셨다면 3월에 좋은 일이...
    "info_fact",            # 125: 진짜 콧털정리 하나만 잘해도 사람 이미지가...
    "info_fact",            # 126: 두산퓨얼셀은 만약 눌리면 -> 이후 크게 한번...
    "emotion_empathy",      # 127: 열심히 공부하세요. 불가능해 보이더라도...
    "info_fact",            # 128: 멕시코 마약왕 '엘 멘초'...
    "info_fact",            # 129: 이런 생각이 든다면 몸이 제발 쉬라고 보내는 신호
    "narrative_situation",  # 130: '히말라야'에서 죽은 주인의 시체를 4일간 지킨...
    "opinion_reaction",     # 131: 컴퓨터 그래픽 제작회사들은 그냥 다 망했다고...
    "info_fact",            # 132: 이제 테슬라 보조금 신청 못받는다는...
    "info_fact",            # 133: 누군가가 와이파이 신호만으로 벽 너머를 볼 수...
    "info_fact",            # 134: 중동 탈출 일본 전세기, 한국인 11명도...
    "promotion",            # 135: 강릉원주대학교, 강원대학교, 경북대학교...
    "info_fact",            # 136: '그러거나 말거나' 회복력 좋은 사람들의 생각 5
    "emotion_empathy",      # 137: 우리는 과도한 자극에 노출되어 있으면서도...
]

LLM_HOOK_LABELS_KR = {
    "narrative_situation": "서사/상황형",
    "info_fact": "정보전달형",
    "opinion_reaction": "의견/반응형",
    "celeb_mention": "셀럽/유명인형",
    "promotion": "홍보/추천형",
    "emotion_empathy": "감정/공감형",
    "comparison_choice": "비교/선택형",
}


def main():
    # hooks_to_classify.json 로드
    with open(BASE_DIR / "hooks_to_classify.json", "r", encoding="utf-8") as f:
        data = json.load(f)

    unclassified = data["unclassified_hooks"]

    assert len(UNCLASSIFIED_LABELS) == len(unclassified), \
        f"분류 개수 불일치: {len(UNCLASSIFIED_LABELS)} != {len(unclassified)}"

    # hook_text → label 매핑 생성
    hook_overrides = {}
    for hook, label in zip(unclassified, UNCLASSIFIED_LABELS):
        hook_overrides[hook["hook_text"]] = label

    # 캐시 저장
    cache = {
        "hook_type_overrides": hook_overrides,
        "labels_kr": LLM_HOOK_LABELS_KR,
    }

    out_path = BASE_DIR / "llm_hook_cache.json"
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(cache, f, ensure_ascii=False, indent=2)

    # 통계
    from collections import Counter
    counts = Counter(UNCLASSIFIED_LABELS)
    print(f"캐시 생성 완료: {out_path.name}")
    print(f"  미분류 Hook 분류: {len(hook_overrides)}건")
    print(f"  유형별 분포:")
    for label, cnt in counts.most_common():
        kr = LLM_HOOK_LABELS_KR.get(label, label)
        print(f"    {kr}: {cnt}건")


if __name__ == "__main__":
    main()
